// Cafe_dsl.ulam.swift
//
// Generated by `stan alist2dsl` from `cafe_dsl.alist.R`.
// Edit `cafe_dsl.alist.R` and re-run `stan alist2dsl` to regenerate.
// The `data` literal carries one stub row per column — actual values
// come from `Preliminaries/cafe_dsl.csv` via `csv2json`.

@main
struct Cafe_dslSmoke {
  static func main() {
    let data: UlamData = [
      "wait": .real([0.0]),
      "J": .scalarInt(2),
      "cafe": .integer([1]),
      "afternoon": .real([0.0]),
      "mu": .real([0.0]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("wait", .normal("mu", "sigma"))
      Deterministic("mu", "a_cafeb_cafe[cafe][1] + a_cafeb_cafe[cafe][2]*afternoon")
      VaryingVectorPrior("a_cafeb_cafe", indexedBy: "cafe", length: "J", .multivariateNormalCholesky(mean: "[a, b]'", chol: "diag_pre_multiply(sigma_cafe, Rho)"))
      Prior("a", .normal(0, 10))
      Prior("b", .normal(0, 10))
      VectorPrior("sigma_cafe", length: "J", .cauchy(0, 2), truncation: Truncation(lower: 0))
      Prior("sigma", .cauchy(0, 2), truncation: Truncation(lower: 0))
      LKJCorrCholeskyPrior("Rho", dim: "J", eta: 2)
    }

    do {
      print(try stancode(model))
      let scalars = stanScalars(model)
      if !scalars.isEmpty {
        print("// === SWIFTSTAN_SCALARS ===")
        print(scalars)
      }
      let inits = try stanInits(model)
      if !inits.isEmpty {
        print("// === SWIFTSTAN_INITS ===")
        print(inits)
      }
    } catch {
      print("ERROR: \(error)")
    }
  }
}
