// Radon_dsl.ulam.swift
//
// Generated by `stan alist2dsl` from `radon_dsl.alist.R`.
// Edit `radon_dsl.alist.R` and re-run `stan alist2dsl` to regenerate.
// The `data` literal carries one stub row per column — actual values
// come from `Preliminaries/radon_dsl.csv` via `csv2json`.

@main
struct Radon_dslSmoke {
  static func main() {
    let data: UlamData = [
      "log_radon": .real([0.0]),
      "floor": .real([0.0]),
    ]

    let model = UlamModel(data: data) {
      Likelihood("log_radon", .normal(.expression("alpha + beta*floor"), "sigma"))
      Prior("alpha", .normal(0, 10))
      Prior("beta", .normal(0, 10))
      Prior("sigma", .normal(0, 10), truncation: Truncation(lower: 0))
    }

    do {
      print(try stancode(model))
      let inits = try stanInits(model)
      if !inits.isEmpty {
        print("// === SWIFTSTAN_INITS ===")
        print(inits)
      }
    } catch {
      print("ERROR: \(error)")
    }
  }
}
